[changelog]
header = """
# Changelog
"""

body = """
{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }}
{% else %}\
    ## Unreleased
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group }}
    {% for commit in commits %}
        - {% if commit.breaking %}**[ ✖_✖ ] BREAKING:** {% endif %}\
          {{ commit.message | upper_first }} \
          ({% if commit.remote.username %}by [@{{ commit.remote.username }}](https://github.com/{{ commit.remote.username }}) via {% endif %}\
          [`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ commit.id }}))\
    {% endfor %}
{% endfor %}\n
"""

footer = """
***
*Generated automatically by Nanoo Labs Pipeline.*
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = false
sort_commits = "newest"

commit_parsers = [
  { message = "^feat(\\(.*\\))?!?:", group = "[^■^] — Features" },
  { message = "^fix(\\(.*\\))?!?:", group = "[;■_■] — Bug Fixes" },
  { message = "^perf(\\(.*\\))?!?:", group = "[█_█] — Performance" },
  { message = "^refactor(\\(.*\\))?!?:", group = "[⌐■_■] — Refactoring" },
  { message = "^doc(\\(.*\\))?s?:", group = "[▦_▦] — Documentation" },
  { message = "^style(\\(.*\\))?!?:", group = "[▣_▣] — Styling & UI" },
  { message = "^ci(\\(.*\\))?!?:", group = "[☁_■] — CI/CD" },
  { message = "^chore(\\(.*\\))?!?:", group = "[▓_▓] — Maintenance" },
  { message = "^test(\\(.*\\))?!?:", group = "[¬■_■] — Testing" },
  { message = ".*", group = "[□_□] — Other" },
]

filter_commits = false
tag_pattern = "v[0-9]*"

[remote.github]
owner = "nanoolabs"
repo = ""
